# Generated by Django 2.1.1 on 2018-09-18 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(blank=True, max_length=3)),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('apellido', models.CharField(blank=True, max_length=20)),
                ('prekills', models.IntegerField()),
                ('postkills', models.IntegerField()),
                ('prewins', models.IntegerField()),
                ('postwins', models.IntegerField()),
                ('general', models.IntegerField()),
                ('verificado', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
