# Generated by Django 2.1.1 on 2018-09-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20180918_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='general',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='postkills',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='postwins',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='prekills',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='prewins',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='verificado',
        ),
    ]
