# Generated by Django 2.1.1 on 2018-09-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_auto_20180920_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='kd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='partidas',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
