# Generated by Django 2.1.1 on 2018-09-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_auto_20180921_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ver',
            field=models.BooleanField(default=False),
        ),
    ]
