# Generated by Django 2.1.1 on 2018-09-22 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_perfil_ver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='ver',
            new_name='VERIFICACION',
        ),
    ]
