# Generated by Django 2.1.1 on 2018-09-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_perfil_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='VERIFICACION',
            new_name='VERIFICACION_1',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='kills',
            new_name='kills_1',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='partidas',
            new_name='kills_2',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='postkills',
            new_name='partidas_1',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='postpartidas',
            new_name='partidas_2',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='postwins',
            new_name='postkills_1',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='prekills',
            new_name='postkills_2',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='prepartidas',
            new_name='postpartidas_1',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='prewins',
            new_name='postpartidas_2',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='wins',
            new_name='postwins_1',
        ),
        migrations.AddField(
            model_name='perfil',
            name='VERIFICACION_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='postwins_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='prekills_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='prekills_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='prepartidas_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='prepartidas_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='prewins_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='prewins_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='twitch_1',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='twitch_2',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='wins_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='wins_2',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
