# Generated by Django 2.1.1 on 2018-09-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_auto_20180929_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='twitch_1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='twitch_2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
