# Generated by Django 2.1.1 on 2018-09-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0023_auto_20180929_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='kills_liga',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='partidas_liga',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='partidas_totales',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
