# Generated by Django 2.1.1 on 2018-10-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0027_auto_20181002_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='partidas_liga',
            new_name='muertes_liga',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='partidas_totales',
            new_name='muertes_totales',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='postpartidas_1',
            new_name='postmuertes_1',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='postpartidas_2',
            new_name='postmuertes_2',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='prepartidas_1',
            new_name='premuertes_1',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='prepartidas_2',
            new_name='premuertes_2',
        ),
    ]
