# Generated by Django 2.1.1 on 2018-10-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0029_auto_20181003_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='partidas_1',
            new_name='muertes_1',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='partidas_2',
            new_name='muertes_2',
        ),
    ]
