# Generated by Django 2.1.1 on 2018-10-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0031_perfil_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='comentario',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
