# Generated by Django 2.1.1 on 2018-10-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0032_auto_20181003_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='kd',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='kills_liga',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='kills_totales',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='muertes_liga',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='muertes_totales',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
    ]
