# Generated by Django 2.1.1 on 2018-11-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0033_auto_20181006_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='black_pan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
