# Generated by Django 2.1.1 on 2018-11-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0038_auto_20181112_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='id1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='id2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
