# Generated by Django 2.1.1 on 2018-09-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20180918_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='general',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postkills',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postwins',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prekills',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prewins',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='verificado',
            field=models.IntegerField(blank=True),
        ),
    ]
