# Generated by Django 2.1.1 on 2018-09-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20180918_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='general',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='postkills',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='postwins',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='prekills',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='prewins',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='verificado',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
