# Generated by Django 2.1.1 on 2018-09-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20180918_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='plataforma',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
