# Generated by Django 2.1.1 on 2018-09-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20180919_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(blank=True, default='a', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, default='a', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='plataforma',
            field=models.CharField(blank=True, default='a', max_length=3),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='twitch',
            field=models.CharField(blank=True, default='a', max_length=20),
        ),
    ]
