# Generated by Django 2.1.1 on 2018-09-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_perfil_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='kills',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='wins',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
