# Generated by Django 2.1.1 on 2018-09-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_auto_20180920_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='kd',
            field=models.CharField(blank=True, default=0, max_length=4),
        ),
    ]
