# Generated by Django 2.1.1 on 2018-09-22 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_auto_20180921_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='verificado',
        ),
    ]
