# Generated by Django 2.1.1 on 2018-10-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0024_auto_20180929_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='general',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='kills_1',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='kills_2',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='partidas_1',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='partidas_2',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postkills_1',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postkills_2',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postpartidas_1',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postpartidas_2',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postwins_1',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postwins_2',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prekills_1',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prekills_2',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prepartidas_1',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prepartidas_2',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prewins_1',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prewins_2',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puntos',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='wins_1',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='wins_2',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
    ]
