# Generated by Django 2.1.1 on 2018-10-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0025_auto_20181001_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='posttop5_1',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pretop5_1',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='top5_1',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
    ]
