# Generated by Django 2.1.1 on 2018-10-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0026_auto_20181002_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='general',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='kills_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='kills_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='partidas_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='partidas_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postkills_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postkills_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postpartidas_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postpartidas_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='posttop5_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postwins_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='postwins_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prekills_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prekills_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prepartidas_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prepartidas_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pretop5_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prewins_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prewins_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puntos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='top5_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='wins_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='wins_2',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
