# Generated by Django 2.1.1 on 2018-10-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0028_auto_20181003_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='postmuertes_1',
            new_name='postpartidas_1',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='postmuertes_2',
            new_name='postpartidas_2',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='premuertes_1',
            new_name='prepartidas_1',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='premuertes_2',
            new_name='prepartidas_2',
        ),
    ]
