# Generated by Django 2.1.1 on 2018-11-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0036_remove_perfil_black_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='black_pan',
            field=models.CharField(blank=True, default='NO', max_length=100),
        ),
    ]
